apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: ftps 
  template:
    metadata:
      labels:
        app: ftps 
    spec:
      containers:
      - name: ftps-service
        image: my_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 10020
        - containerPort: 10021

---      

apiVersion: v1
kind: Service
metadata:
    name: ftps-service
    annotations:
        metallb.universe.tf/allow-shared-ip: sharing key
spec:
    type: LoadBalancer
    selector:
        app: ftps 
    ports:
        - name: ftps
          protocol: TCP
          port: 21
        - name: passive-min
          protocol: TCP
          port: 10020
        - name: passive-max
          protocol: TCP
          port: 10021
