apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana 
    spec:
      containers:
      - name: grafana
        image: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

---      

apiVersion: v1
kind: Service
metadata:
    name: grafana
    annotations:
        metallb.universe.tf/allow-shared-ip: sharing key
spec:
    type: LoadBalancer
    selector:
        app: grafana 
    ports:
        - protocol: TCP
          port: 3000