apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: mysql 
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
      - name: mysql-service
        image: my_mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306

---      

apiVersion: v1
kind: Service
metadata:
    name: mysql-service
spec:
    selector:
        app: mysql 
    ports:
        - protocol: TCP
          port: 3306

