apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: my_nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443

---      

apiVersion: v1
kind: Service
metadata:
    name: nginx
    annotations:
        metallb.universe.tf/allow-shared-ip: sharing key
spec:
    type: LoadBalancer
    selector:
        app: nginx
    ports:
        - name: http
          protocol: TCP
          port: 80
        - name: https
          protocol: TCP
          port: 443
        - name: ssh
          protocol: TCP
          port: 22

