apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin 
  template:
    metadata:
      labels:
        app: phpmyadmin 
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
       
---      

apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin
    annotations:
        metallb.universe.tf/allow-shared-ip: sharing key
spec:
    type: LoadBalancer
    selector:
        app: phpmyadmin
    ports:
        - protocol: TCP
          port: 5000
