apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: phpmyadmin 
  template:
    metadata:
      labels:
        app: phpmyadmin 
    spec:
      containers:
      - name: phpmyadmin-service
        image: my_phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

---      

apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin-service
    annotations:
        metallb.universe.tf/allow-shared-ip: sharing key
spec:
    type: LoadBalancer
    selector:
        app: phpmyadmin 
    ports:
        - protocol: TCP
          port: 5000

