apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress 
  template:
    metadata:
      labels:
        app: wordpress 
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

---      

apiVersion: v1
kind: Service
metadata:
    name: wordpress
    annotations:
        metallb.universe.tf/allow-shared-ip: sharing key
spec:
    type: LoadBalancer
    selector:
        app: wordpress 
    ports:
        - protocol: TCP
          port: 5050