apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: wordpress 
  template:
    metadata:
      labels:
        app: wordpress 
    spec:
      containers:
      - name: wordpress
        # env:
        # - name: WORDPRESS_DB_HOST
        #   value: mysql-service
        # - name: WORDPRESS_DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-pass
        #       key: password
        image: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim

---      

apiVersion: v1
kind: Service
metadata:
    name: wordpress
    annotations:
        metallb.universe.tf/allow-shared-ip: sharing key
spec:
    type: LoadBalancer
    selector:
        app: wordpress 
    ports:
        - protocol: TCP
          port: 5050
          targetPort: 5050

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
